# Generated by Django 5.2.16 on 2026-07-09 09:56

# Django
from django.db import migrations, models

# AA SRP
import aasrp.models


class Migration(migrations.Migration):

    dependencies = [
        ("aasrp", "0002_migrate_to_sde"),
        ("authentication", "0026_alter_characterownership_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestcomment",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=models.SET(aasrp.models.get_sentinel_user),
                related_name="+",
                to="authentication.user",
                verbose_name="Creator",
            ),
        ),
        migrations.AlterField(
            model_name="srplink",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Who created the SRP link?",
                null=True,
                on_delete=models.SET(aasrp.models.get_sentinel_user),
                related_name="+",
                to="authentication.user",
                verbose_name="Creator",
            ),
        ),
        migrations.AlterField(
            model_name="srprequest",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Who created the SRP request?",
                null=True,
                on_delete=models.SET(aasrp.models.get_sentinel_user),
                related_name="+",
                to="authentication.user",
                verbose_name="Creator",
            ),
        ),
        migrations.AlterField(
            model_name="usersetting",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=models.SET(aasrp.models.get_sentinel_user),
                related_name="+",
                to="authentication.user",
                verbose_name="User",
            ),
        ),
    ]
