# Generated by Django 3.1.3 on 2020-11-09 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0012_index_additions"),
        ("aasrp", "0002_auto_20201106_1258"),
    ]

    operations = [
        migrations.AddField(
            model_name="aasrprequest",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="eveonline.evecharacter",
            ),
        ),
        migrations.AlterField(
            model_name="aasrprequest",
            name="character",
            field=models.CharField(default="", max_length=254),
        ),
    ]
