# Generated by Django 4.0.6 on 2022-07-30 20:24

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aasrp", "0006_related_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aasrprequestcomment",
            name="comment_type",
            field=models.CharField(
                choices=[
                    ("Comment", "Comment"),
                    ("Request Information", "Additional Information"),
                    ("Reject Reason", "Reject Reason"),
                    ("Status Changed", "Status Changed"),
                    ("Reviser Comment", "Reviser Comment"),
                ],
                default="Comment",
                max_length=19,
            ),
        ),
    ]
