# Generated by Django 4.0.6 on 2022-07-30 12:09

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aasrp", "0006_related_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aasrprequestcomment",
            name="comment_type",
            field=models.CharField(
                choices=[
                    ("Comment", "SRP Request Comment"),
                    ("Request Information", "SRP Request Additional Information"),
                    ("Reject Reason", "SRP Reject Reason"),
                    ("Reviser Comment", "SRP Request Reviser Comment"),
                ],
                default="Comment",
                max_length=19,
            ),
        ),
    ]
