# Generated by Django 4.0.7 on 2022-08-04 18:20

# Django
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aasrp", "0007_aasrprequestcomment_comment_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aasrprequestcomment",
            name="new_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                max_length=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="aasrprequestcomment",
            name="comment_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
