# Generated by Django 4.0.10 on 2023-06-20 15:21

# Django
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eveonline", "0017_alliance_and_corp_names_are_not_unique"),
        ("eveuniverse", "0010_alter_eveindustryactivityduration_eve_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("aasrp", "0009_add_fleet_type_to_srp_link"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AaSrpInsurance",
            new_name="Insurance",
        ),
        migrations.RenameModel(
            old_name="AaSrpRequestComment",
            new_name="RequestComment",
        ),
        migrations.RenameModel(
            old_name="AaSrpLink",
            new_name="SrpLink",
        ),
        migrations.RenameModel(
            old_name="AaSrpRequest",
            new_name="SrpRequest",
        ),
        migrations.RenameModel(
            old_name="AaSrpUserSettings",
            new_name="UserSetting",
        ),
    ]
