# Generated by Django 4.0.10 on 2023-06-22 14:32

# Django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aasrp", "0010_change_model_names_and_verobose_names"),
    ]

    operations = [
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "srp_team_discord_channel_id",
                    models.PositiveBigIntegerField(
                        default=None,
                        null=True,
                        verbose_name="SRP Team Discord Channel ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "setting",
                "verbose_name_plural": "settings",
                "default_permissions": (),
            },
        ),
    ]
